version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmquser
      - RABBITMQ_DEFAULT_PASS=DEBmbwkSrzy9D1T9cJfa
      
  sqlserver:
    image: microsoft/mssql-server-linux:latest
    container_name: sqlserver
    volumes:
      - sqlserverdata:/var/opt/mssql 
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_PID=Developer
      - SA_PASSWORD=8jkGh47hnDw89Haq8LN2
  mongo:
    image: mongo
    ports:
    - "27017:27017"
#    volumes:
#    - mongodata:/data/db

  logserver:
    image: datalust/seq:latest
    container_name: logserver
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y

  patientaccountapi:
    image: solutionarchitectureassignment/patientaccountapi:latest
    build: ./PatientAccountAPI
#    depends_on:
#      - rabbitmq
#      - mongo
    links:
      - mongo
    ports:
      - "8000:8000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  timeservice:
    image: solutionarchitectureassignment/timeservice:latest
    build: TimeService
    container_name: timeservice
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

volumes:
  sqlserverdata:
    external: true    
  rabbitmqdata:
    external: true
#  mongodata:
#    external: true
    